#!/usr/bin/env bash

script_dir="$HOME/.config/eww/script"


monitor=$("$script_dir/focused_monitor")

handle() {
  case $1 in
    activewindow*) 
      {
        "$script_dir/list_workspaces" "$monitor"
      };;
    workspace*) 
      {
        "$script_dir/list_workspaces" "$monitor"
      };;
    focusedmon*)
      {
        monitor=$("$script_dir/focused_monitor")
        "$script_dir/list_workspaces" "$monitor"
      };;

  esac
}

socat -U - UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock | while read -r line; do handle "$line"; done
