#!/usr/bin/env bash

script_dir="$HOME/.config/eww/script"
handle() {
  case $1 in
    activewindow*) 
      {
        "$script_dir/list_workspaces" DP-1
      };;
    workspace*) 
      {
        "$script_dir/list_workspaces" DP-1
      };;
  esac
}

socat -U - UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock | while read -r line; do handle "$line"; done
