#!/usr/bin/env bash
#
# Check if the argument is provided
if [[ -z "$1" ]]; then
    echo "Please provide the switch argument (e.g., DP-1)"
    exit 1
fi

# Run the command and capture its output
output=$(hyprctl workspaces | grep "$1" | awk '{print substr($4, 2, length($4)-2)}')

# Extract the numbers, sort them, and format the output
# sorted_numbers=$(echo "$output" | sort -V | awk '{print "(button :class \"workspace btn\" \x27" $1 "\x27)"}' | tr '\n' ' ' | sed 's/ $//')
sorted_numbers=$(echo "$output" | sort -V | awk '{print "(eventbox :class \"workspace eventbox\" :onhover \"do hover\" :tooltip \"a tooltip\" \x27" $1 "\x27)"}' | tr '\n' ' ' | sed 's/ $//')
formatted_output="(box $sorted_numbers)"

# Print the result
echo "$formatted_output"
