#!/usr/bin/env bash
#
# Check if the argument is provided
if [[ -z "$1" ]]; then
    echo "Please provide the switch argument (e.g., DP-1)"
    exit 1
fi

# Run the command and capture its output
output=$(hyprctl workspaces | grep "$1" | awk '{print substr($4, 2, length($4)-2)}')

# Extract the numbers, sort them, and format the output
# sorted_numbers=$(echo "$output" | sort -V | awk '{print "(button :class \"workspace btn\" \x27" $1 "\x27)"}' | tr '\n' ' ' | sed 's/ $//')
sorted_numbers=$(echo "$output" | sort -V | awk \
    '{print "(eventbox \
        :class \"workspace eventbox\" \
        :tooltip \"a tooltip\" \
        :onclick \"hyprctl dispatch workspace \x27" $1 "\x27\" \
        (label :width 25 :limit-width 60 :text \"\x27" $1 "\x27\"))"}' \
        |tr -s ' '|tr '\n' ' '|sed "s/'//g")
        formatted_output="(box $sorted_numbers)"

current_workspace=$(hyprctl activewindow|grep workspace:|cut -d" " -f3|cut -d"(" -f2|cut -d")" -f1)

# echo "current_workspace: $current_workspace"
# echo "$formatted_output"
# echo "---------------"
# formatted_output='(box (eventbox :class "workspace eventbox" :tooltip "a tooltip" :onclick "hyprctl dispatch workspace 8" (label :width 25 :limit-width 60 :text "8")) (eventbox :class "workspace eventbox" :tooltip "a tooltip" :onclick "hyprctl dispatch workspace Ai" (label :width 25 :limit-width 60 :text "Ai")) (eventbox :class "workspace eventbox" :tooltip "a tooltip" :onclick "hyprctl dispatch workspace Flee" (label :width 25 :limit-width 60 :text "Flee")) (eventbox :class "workspace eventbox" :tooltip "a tooltip" :onclick "hyprctl dispatch workspace Safer" (label :width 25 :limit-width 60 :text "Safer")) )'
# current_workspace="Safer"

# Split formatted_output into an array of eventboxes
IFS=")" read -r -a eventboxes <<< "$formatted_output"

# Iterate over each eventbox
for (( i=0; i<${#eventboxes[@]}; i++ )); do
    if [[ "${eventboxes[i]}" == *":text \"$current_workspace\""* ]]; then
        # Replace class value with "workspace eventboxfocus"
        eventboxes[i]="${eventboxes[i]/\"workspace eventbox\"/\"workspace eventboxfocus\"}"
    fi
done

# Merge modified eventboxes back into formatted_output
modified_output="$(IFS=")"; echo "${eventboxes[*]}")"

echo "$modified_output)"
