#!/usr/bin/env bash

# Capture the command output in a variable
monitor_info=$(hyprctl workspaces)

# Split the output by lines starting with "^Monitor" and store them in an array
monitor_list=($(awk '/^workspace/' <<< "$monitor_info"))


# Loop through the array and print each element (monitor information block)
for monitor in "${monitor_list[@]}"; do
  echo "$monitor"
  echo "-------------"
done
